### ISSUE TITLE
Is it possible to train other estimation like fingertip?

### ISSUE THREAD

**Issue by tucan9389** [edvardHua/PoseEstimationForMobile#11]
I have fingertip dataset that are images + label, and I want to train the dataset.
Is it possible to train fingertip estimation by using this project?

#### label format:
```
I_Fountain_xxx.png tlx tly brx bry ftx fty jntx jnty tjntx tjnty 0 0 0 0
I_RenwenBuilding_xxx.png tlx tly brx bry ftx fty jntx jnty tjntx tjnty 0 0 0 0
I_Chinesebook_xxx.png tlx tly brx bry ftx fty jntx jnty tjntx tjnty 0 0 0 0
```
- `tlx && tly`: bounding box top-left point (x, y)
- `brx&& bry`: bounding box bottom-right point (x, y)
- `ftx && fty`: fingertip point (x, y)
- `jntx&&jnty`:	index finger joint point (x, y)
- `tjntx&&tjnty`: tail finger joint point (x, y)

Thanks always.

**Comment by edvardHua** [comment]
Yes, it can. But need to modify the code of input and output. I will try it if I have time.  😁

**Comment by tucan9389** [comment]
I also attempt for my study now 🤓
Should it be changed many codes for that? I think just change only `n_kpoints: 14` on `mv2_cpm.cfg` and some `dataset.py` code. 
Could you advise something to me?🙏

**Comment by edvardHua** [comment]
You also need to change annotations format.

**Comment by tucan9389** [comment]
<img width="1517" alt="screen shot 2018-07-10 at 6 50 29 am" src="https://user-images.githubusercontent.com/37643248/42481061-64285dfa-841b-11e8-8a41-2f36ae124139.png">
I finally success! Thanks for advise🙇‍♂️. @edvardHua
