### ISSUE TITLE
Use validation dataset when 'pred_image_on_tensorboard'

### ISSUE THREAD

**Issue by tucan9389** [edvardHua/PoseEstimationForMobile#17]
I have customized and ran this project. 
One of the customized feature is that using validation dataset(`ai_challenger_valid.json`) when 'pred_image_on_tensorboard' on `training.py`. 
Could you review this feature after I PR?

**Comment by edvardHua** [comment]
Great, I will review it. 😁

**Comment by tucan9389** [comment]
I PR just now. plz check #18 
Thank you :)
