### ISSUE TITLE
数据增强 pose_crop_random是不是有问题

### ISSUE THREAD

**Issue by sijun-zhou** [edvardHua/PoseEstimationForMobile#37]
@edvardHua 你好，很感谢你的代码，但是我有两点疑问，如下
pose_crop_random 函数如下：

def pose_crop_random(meta):
    global _network_w, _network_h
    target_size = (_network_w, _network_h)
    for _ in range(50):
        x = random.randrange(0, meta.width - target_size[0]) if meta.width > target_size[0] else 0
        y = random.randrange(0, meta.height - target_size[1]) if meta.height > target_size[1] else 0

        # check whether any face is inside the box to generate a reasonably-balanced datasets
        for joint in meta.joint_list:
            if x <= joint[CocoPart.RKnee.value][0] < x + target_size[0] and \
                    y <= joint[CocoPart.RKnee.value][1] < y + target_size[1] and \
                    x <= joint[CocoPart.RAnkle.value][0] < x + target_size[0] and \
                    y <= joint[CocoPart.RAnkle.value][1] < y + target_size[1] and \
                    x <= joint[CocoPart.LKnee.value][0] < x + target_size[0] and \
                    y <= joint[CocoPart.LKnee.value][1] < y + target_size[1] and \
                    x <= joint[CocoPart.LAnkle.value][0] < x + target_size[0] and \
                    y <= joint[CocoPart.LAnkle.value][1] < y + target_size[1]:
                break
    return pose_crop(meta, x, y, target_size[0], target_size[1])

if条件是检测左右的膝盖和脚踝是否都在256的输入范围内，但是根据代码的意思，满足了这个条件就break了，break了内层循环，继续外层的50次循环。这个时候不是应该是找到了满意的x,y就应该直接调用pose_crop函数才对吗？

另外还有第二个问题，只检查膝盖和脚踝这两个部位，条件充足吗？万一有的人的14个的点中其他位置超过了256输入的范围高斯图ground true怎么处理？丢弃还是什么？

**Comment by accountcwd** [comment]
我也注意到了，这个数据增强的方法应该是借用[ildoonet/tf-pose-estimation](https://github.com/ildoonet/tf-pose-estimation)实现的，不过他那里是检测头部，实际上就是做了50次随机裁剪取最后一次，超出范围的点在后续的函数里被丢弃了。不过照这样做也能能复现原PO的效果。

**Comment by edvardHua** [comment]
@sijun-zhou @accountcwd 现在细看的确是有问题，应该把 break 放到外面那层循环，另外，因为下体的关键点检测精度不高，所以这里随机裁剪的时候，尽量不把下体裁剪掉。
