### ISSUE TITLE
如何去掉不合理的连线呢？

### ISSUE THREAD

**Issue by fangliang321** [edvardHua/PoseEstimationForMobile#38]
不是全身时就会发生连线混乱。

**Comment by edvardHua** [comment]
过滤热图的阈值 + 一些身体结构的判断就可以去掉不合理的连线了。

**Comment by lzcchl** [comment]
人体的姿态千千万，请问您说的身体结构判断大概是怎么处理呢？有比较稳定的连线在实际使用体验中特别重要

**Comment by lzcchl** [comment]
人体的姿态千千万，请问您说的身体结构判断大概是怎么处理呢？有比较稳定的连线在实际使用体验中特别重要
