### ISSUE TITLE
请问：inference time 20ms 左右的时间是基于mace的还是tflite的

### ISSUE THREAD

**Issue by ChuanchuanZheng** [edvardHua/PoseEstimationForMobile#39]
看到README里面的gif的响应时间是20ms左右，请教一下这个时间是基于mace实现还是基于tflite？在什么手机上是这样的效果呢？我重新只训练腿部节点，得到的模型经过tflite unit8的量化之后在荣耀8的手机上还是150ms左右。

**Comment by edvardHua** [comment]
是基于 mace 的。

**Comment by ChuanchuanZheng** [comment]
@edvardHua 你tflite经过unit8的量化吗？我在用fake quantization生成min/max节点的时候发现有一些relu节点没有生成对应的min/max节点，请问你有碰到过吗？

**Comment by edvardHua** [comment]
@ChuanchuanZheng 我并没有去量化，准备去尝试，有结果的话会更新仓库的。

**Comment by edvardHua** [comment]
@ChuanchuanZheng 我试了一下量化，是生成 quant graph 来训练，没有生成 min/max 节点的原因是因为 delay_quant 要设置成差不多收敛时的步数。

```
tf.contrib.quantize.create_training_graph(
    input_graph=None,
    quant_delay=30000 # 这里设置成差不多收敛的步数
)
```

但是，我发现量化后，好像预测结果有问题。。。
