### ISSUE TITLE
CPU速度非常慢

### ISSUE THREAD

**Issue by flyingzhao** [edvardHua/PoseEstimationForMobile#41]
将代码改为`JniMaceUtils.maceMobilenetCreateEngine("cpm_v1", "CPU");`，CPU速度非常慢，在小米8上需要500ms，而tflite只有120ms。

**Comment by flyingzhao** [comment]
在我看来，都是neon加速的，应该差别不会这么大啊。等我后面profiling一下模型，看看哪边耗时了

**Comment by edvardHua** [comment]
哈哈，期待你的分析结果。

**Comment by flyingzhao** [comment]
我分别profiling了两个框架CPU推断的时间，在小米8上tflite约为100ms，mace约为150ms。mace的benchmark时间和工程实现有差异，我正在检查。 @edvardHua

**Comment by WinstonDeng** [comment]
@flyingzhao 请问 demo_tflite 是如何 build 的呢？我在 ubuntu 16 上一直卡在 c/c++ 的报错上，想问下能否提供一个工程构建的指导步骤，非常感谢！
