### ISSUE TITLE
How can I measure accuracy(or other metric) on mobile?

### ISSUE THREAD

**Issue by tucan9389** [edvardHua/PoseEstimationForMobile#49]
Hi again!
I want to measure the accuracy(or other metrics) on iOS for testing model quantization of Core ML. Do you have any advice?

**Comment by edvardHua** [comment]
I think you can run the quantization model on macOS for testing accuracy.

**Comment by edvardHua** [comment]
[benchmark.py](https://github.com/edvardHua/PoseEstimationForMobile/blob/master/training/src/benchmark.py) ?，or you want to measure the different of output between quantized and unquantized model by using `l2` loss function.

**Comment by tucan9389** [comment]
Thanks a lot :)
