### ISSUE TITLE
[Question] Model converting information

### ISSUE THREAD

**Issue by nanamare** [edvardHua/PoseEstimationForMobile#51]
Hi.
I have some question.

Which option did you choose model converting?
ex) obfuscate, Winograd, limit_opencl_kernerl_time, runtime etc..

I want to make the fastest model as soon as possible, don't care - take more memory.
I have changed options(winograd = 4 etc..) But it does not work.

Thanks! HF

**Comment by edvardHua** [comment]
The same as [cpm.yml](https://raw.githubusercontent.com/edvardHua/PoseEstimationForMobile/master/release/mace_ymls/cpm.yml). 😁
