### ISSUE TITLE
support for training on mac

### ISSUE THREAD

**Issue by tucan9389** [edvardHua/PoseEstimationForMobile#58]
Hi again! I want to run `train.py` on my mac. But mac does not support gpu. May I PR for that?

**Comment by edvardHua** [comment]
It seems tensorflow not support gpu training on mac.

**Comment by tucan9389** [comment]
Yes so, I want to PR for CPU only option in ‘train.py’.

**Comment by edvardHua** [comment]
That was good if you PR for this.  😁

**Comment by tucan9389** [comment]
@edvardHua plz check this out #59. :)

**Comment by edvardHua** [comment]
Done.
