### ISSUE TITLE
I want to convert to model for Core ML that is iOS ML framework(Done).

### ISSUE THREAD

**Issue by tucan9389** [edvardHua/PoseEstimationForMobile#6]
Hi, I'm iOS developer and I want to run this model on iOS.
I found `tflite` model, but I need `frozen pb` model for converting to Core ML model.
Can I get frozen `pb` model?

**Comment by edvardHua** [comment]
@tucan9389 Of course, the `forzen pb` and `mlmodel`  is already contains in [here](https://github.com/edvardHua/PoseEstimationForMobile/tree/master/release/cpm_model).

**Comment by tucan9389** [comment]
Oh, thanks a lot!

**Comment by tucan9389** [comment]
Is there project working for iOS with this pose estimation model, currently?

Sorry for bad english.

**Comment by edvardHua** [comment]
https://github.com/infocom-tpo/SwiftOpenPose

Maybe above repo can help you, but `openpose` calculation is too large.

**Comment by tucan9389** [comment]
https://github.com/tucan9389/PoseEstimation-CoreML
Here I make iOS project for pose estimation!

## Performance
It was measured **60-110mm for execution time** and **9-13 fps** on iPhone X.
### execution time: 
`model inference time` + `converting time` from heatmap to point array + `rendering time`

![image](https://github.com/tucan9389/PoseEstimation-CoreML/raw/master/resource/180705-poseestimation-demo.gif?raw=true)

Thanks for helping me! :)

**Comment by edvardHua** [comment]
@tucan9389 It's great. I will release the new model which inference faster than old one in the coming few days. Stay tuned.

**Comment by tucan9389** [comment]
It's interesting🙃. Is it the same model format(shape) for input/output node compared to the previous model?
```
input: 224 x 224 x 3
output: 112 x 112 x 14 [top, neck,   R shoulder, R elbow, R wrist, L shoulder, L elbow, L wrist,   R hip, R knee, R ankle, L hip, L, knee, L ankle]
```

**Comment by tucan9389** [comment]
How did you get that coreml model? Did you write script file converting to mlmodel?
@edvardHua

**Comment by edvardHua** [comment]
By using [coremltool](https://github.com/apple/coremltools), it can convert tf model to mlmodel.

**Comment by tucan9389** [comment]
Thanks
