### ISSUE TITLE
你好，各个模型的输出含义是什么呢

### ISSUE THREAD

**Issue by candrwow** [edvardHua/PoseEstimationForMobile#64]
我阅读了你提供的yml文件，但是其中我有一点不太明白，output_shapes的张量含义是什么呢？[1,96,96,14]这里的96，14分别是？目前我的理解是将原图缩小1/4后各坐标的人体部位概率，不知道这样是否理解正确呢？另外我有个疑惑，该项目在单独处理图片时是否可以去除opencv等其他第三方处理库，直接通过缩放输入图片三通道像素值，得到结果的概率呢？并不需要绘制人体线条。
谢谢你的帮助

**Comment by edvardHua** [comment]
1 batch size
96x96 feature map size 每个热图最大值就是关键点位置
14 channels 14 个关键点
可以去掉 opencv 的，你可以自行修改
