### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by streetdijk** [edvardHua/PoseEstimationForMobile#73]
When I build the project, I get an error message saying 'Cause: executing external native build for cmake CmakeList.txt'.

can you tell me a workaround that you can build without errors.

**Comment by streetdijk** [comment]
> When I build the project, I get an error message saying 'Cause: executing external native build for cmake CmakeList.txt'.
> 
> can you tell me a workaround that you can build without errors.

**Comment by streetdijk** [comment]
> 

> @ #

**Comment by streetdijk** [comment]
> When I build the project, I get an error message saying 'Cause: executing external native build for cmake CmakeList.txt'.
> 
> can you tell me a workaround that you can build without errors.

**Comment by tgpsantos** [comment]
I'm also facing the same problem
