### ISSUE TITLE
Why use lambda instead of primitive type (like an integer) on network_mv2_hourglass.py

### ISSUE THREAD

**Issue by tucan9389** [edvardHua/PoseEstimationForMobile#76]
Hi, I'm doing for building my own model by referencing your code and I have some questions.

in `trainting/src/network_mv2_hourglass.py`
![image](https://user-images.githubusercontent.com/37643248/57208966-6bfcdf00-7011-11e9-9ed7-471ed26b4abd.png)
![image](https://user-images.githubusercontent.com/37643248/57208977-761edd80-7011-11e9-81a6-a49f0f03eaec.png)

1. Is it possible to use it like below instead of above?
2. Is there any reason for the above code?

```python
net = slim.stack(net, inverted_bottleneck,
                     [
                         (6, 24, 1, 3),
                         (6, 24, 0, 3),
                         (6, 24, 0, 3),
                         (6, 24, 0, 3),
                         (6, 24, 0, 3),
                     ], scope="Conv2d_2")
```

Thanks 😁

**Comment by edvardHua** [comment]
1. Yes, it possible.
2. The function of up_channel_ratio and out_channel_ratio make network structure easier to scaleable. (big or small computation)

**Comment by tucan9389** [comment]
I see. Thanks for replying.
