### ISSUE TITLE
Hand pose estimation

### ISSUE THREAD

**Issue by AndrGolubkov** [edvardHua/PoseEstimationForMobile#86]
Hey. I know that I am not the first to ask this, but I decided by your example and data from http://domedb.perception.cs.cmu.edu/handdb.html to do hand pose estimation. But my knowledge is not enough to adjust the learning itself. The model will have 21 key points. Can you tell in which places and what needs to be corrected in code? In addition to the configuration of course. Thanks in advance for the hint and sorry for my bad english

**Comment by edvardHua** [comment]
You need to create you own dataset.

1. put the image into one folder.
2. write the keypoint annotation into json file with coco format (like the [dataset](https://drive.google.com/file/d/1zahjQWhuKIYWRRI2ZlHzn65Ug_jIiC4l/view) i provide).
3. modify the dataset augment code.

**Comment by AndrGolubkov** [comment]
With the first two points - no difficulties, I prepared the data set. I understand that I need to edit 2 files - dataset_prepare.py and dataset_augment.py. But it is not completely clear what needs to be changed. If it's not difficult for you, could you tell?

**Comment by bao-O** [comment]
@AndrGolubkov I'm facing a problem when preparing dataset for training a custom model. I don't know what is "area" value in the json file. Is it multiplied by height and width values of the object's bounding box?

**Comment by aitikgupta** [comment]
> @AndrGolubkov I'm facing a problem when preparing dataset for training a custom model. I don't know what is "area" value in the json file. Is it multiplied by height and width values of the object's bounding box?

You're right.
'area' is just the multiplication of bbox[3] * bbox[4], where bbox[3] is the width and bbox[4] is the height.

**Comment by utkarshvermaa** [comment]
> 
> 
> With the first two points - no difficulties, I prepared the data set. I understand that I need to edit 2 files - dataset_prepare.py and dataset_augment.py. But it is not completely clear what needs to be changed. If it's not difficult for you, could you tell?

@AndrGolubkov can you help me with what all modifications did you do for your custom dataset? I am kind of stuck on a similar problem. Thanks!
